from private_conf import TOKEN_BOT, MAIL_PASSWORD1, MAIL_USERNAME1, SECRET_KEY1

DEBUG = True
CSRF_ENABLED = True
SECRET_KEY = SECRET_KEY1
SQLALCHEMY_DATABASE_URI = 'sqlite:///vocab.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = False
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = MAIL_USERNAME1
MAIL_PASSWORD = MAIL_PASSWORD1
TOKEN = TOKEN_BOT
NGROK_URI = "https://6675db3f2a73.ngrok.io"
API_KEY = "7a861b97b1msh795315f8cc4e24dp17d59ajsn01d1cb5156cb"
ELASTICSEARCH_URL = "http://localhost:8443"
